name: rick tham
favicon: null
layout_spectrum: 0.7525744717568159
typography_spectrum: 0.760367777897045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2812298075295985
  lightness: 0.9356221917551011
  saturation: 0.4417548351921141
  rhythmicContrast: 0.21140846679918468
purpose: []
